"""
Dynamical mode decomposition (DMD)

DMD is a data-driven method to obtain spatial-temporial coherent modes from data
It is generally given data of a complex high dimensional non-linear system and evaluates
the best linear fit to the data, providing the dominant coherent modes (dimension reduction).

Theory:
The algorithm postulates that the data is generated by a linear dynamical system, x_{t+1} = A x_t, where A = X' X^\dagger,
where X = data[:, :-1] and X' = data[:, 1:]. The algorithm includes a partial singular value decomposition (SVD) of X, 
leading to a reduced space representation of the linear operator A. Next, the eigenvalues and eigenvectors of the
reduced space linear operator are evaluated, and the dynamical modes are given by the eigenvectors of the reduced space linear operator,
mapped back to the original space.

Complexity: The algorithm requires O(d*n*r) time to compute the partial SVD, where d is the dimension of the state space, n is the number of time steps,
and r is the number of modes returned. The eigenvalue decomposition of the reduced space linear operator requires O(r^3) time.
"""
import numpy as np
from scipy.sparse.linalg import svds

def dynamical_mode_dedcomposition(data: np.ndarray, r: int) -> tuple[np.ndarray, np.ndarray]:
    """
    Evaluates the m most dominant dynamical modes, best describing the data.
    
    Args:
        data (np.ndarray): dynamical data, the columns corresponds to state vectors at
                            increasing times.
        r (int): number of dynamical modes returned

    Returns:
        np.ndarray, containing the columns are the m most dynamical modes
    """
    U, S, Vt = svds(data[:, :-1], k=r)  # only top-r components, dimensions: U (d,r), S (r,), Vt (r, d), where d=data.shape[0]
    V = Vt.conj().T
    A_reduced = U.conj().T @ data[:, 1:] @ (V / S)  # reduced space linear operator, dimensions: (r,r).  V / S is equivalent to V @ np.linalg.inv(np.diag(S)).
    E, W = np.linalg.eig(A_reduced)
    return data[:, 1:] @ (V / S) @ W    # dynamical modes are given by the eigenvectors of the reduced space linear operator,
                                         # mapped back to the original space.


if __name__ == "__main__":

    # generate synthetic data
    np.random.seed(42)
    n = 100  # number of time steps
    d = 500   # dimension of the state space
    r = 5    # number of dynamical modes

    # create r random DMD modes and stable eigenvalues
    modes = np.random.rand(d, r) + 1j * np.random.rand(d, r)
    eigenvalues = np.exp(1j * np.random.rand(r) * 2 * np.pi) * 0.99  # stable: |λ| < 1

    # generate data as superposition of modes evolving at their eigenfrequencies
    # x(t) = sum_i λ_i^t * mode_i. The columns of data are the state vectors at increasing times, so data[:, t] = x(t).
    data = np.zeros((d, n), dtype=complex)
    for t in range(n):
        data[:, t] = modes @ (eigenvalues ** t)

    # apply DMD to recover the dominant modes
    recovered_modes = dynamical_mode_dedcomposition(data, r)

    # compare using best-match overlap (modes may be in different order)
    overlaps = np.zeros((r,))
  
    for i in range(r):
        best_overlap = 0
        for j in range(r):
            overlap = np.abs(np.dot(recovered_modes[:, i].conj(), modes[:, j])) / (np.linalg.norm(recovered_modes[:, i]) * np.linalg.norm(modes[:, j]))
            best_overlap = max(best_overlap, overlap)
        overlaps[i] = best_overlap

    assert np.all(overlaps > 0.9), "Recovered modes do not match the original modes well."
    print("DMD successfully recovered the dominant modes with high overlap.")

